name       : perl-pcsc
version    : 1.4.14
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/W/WH/WHOM/pcsc-perl-1.4.14.tar.bz2 : 2722b7e5543e4faf3ba1ec6b29a7dfec6d92be1edec09d0a3191992d4d88c69d
license    : GPL-2.0-or-later
component  : programming.perl
summary    : Perl interface to the PC/SC smart card library
description: |
    This library allows to communicate with a smart card using PC/SC
    interface (pcsc-lite) from a Perl script.
builddeps  :
    - pkgconfig(libpcsclite)
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
